git:
  depth: 1
  quiet: true

branches:
  only:
    - master

language: c

addons:
  apt:
    packages:
      - fakeroot
      - groff
  homebrew:
    packages:
      - fakeroot
      - groff

script:
  - autoreconf -i
  - ./configure --enable-compiler-warnings
  - make check
  - ./tests-show-results
  - make distcheck

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode10.2
